### ISSUE TITLE
Failed To Add Team Member

### ISSUE THREAD

**Issue by euclidian** [OpenSRP/openmrs-module-team#1]
I'm trying to add team member to a team in openmrs for authentication. But I got this error:

An Internal Error has Occurred
java.lang.ClassCastException
org.openmrs.Location cannot be cast to java.util.Collection
Installed module :

Serialization Xstream   0.2.7
Reporting   0.9.3
Team Management Module  0.1.0A
HTML Form Entry Extensions for OpenMRS 1.9 Module   1.5
Logic Module    0.5.2
HTML Form Entry 2.5
OpenMRS UI Framework    3.3.1
Rest Web Services   2.11.dae2e2
HTML Widgets    1.6.7
Calculation 1.1

Have tried several OpenMRS version : 2.2, 1.9, 1.11.2, 1.11.3 and still failed.

Is there anything that I miss?

**Comment by sohelsarder** [comment]
Hi there, 
I did experience similar problem, I am not sure which teammanagement module version you tried,
https://drive.google.com/file/d/0B-eTkXYbNA9eNWVDMkFuZVdhWkk/view?usp=sharing works for me.

**Comment by euclidian** [comment]
What version of OpenMRS do you use? Is it the platform war or the standalone version?

**Comment by euclidian** [comment]
Nevermind, your version works for me.

Thanks
