### ISSUE TITLE
Search member by location not working

### ISSUE THREAD

**Issue by maimoonak** [OpenSRP/openmrs-module-team#2]
The link is supposed to retrun all team members in this location http://46.101.51.199:8080/openmrs/ws/rest/v1/teammodule/memberLocation?q=korangi

But it is throwing an exception. Please look into it urgently.

Class handling this is https://github.com/OpenSRP/openmrs-module-team/blob/master/omod/src/main/java/org/openmrs/module/teammodule/web/resource/LocationRequestResource.java

@maina

**Comment by MohammadSafwan** [comment]
Adding "&v=full" at the end will resolve the issue. It's because it doesn't returns the values in custom representation and brings the data in full representation. 
Also, it brings the member mapped on the location being searched.

**Comment by maina** [comment]
@MohammadSafwan am accessing the Indonesian server OpenMRS instance and still getting an exception.
<img width="1678" alt="screen shot 2016-06-10 at 1 59 18 pm" src="https://cloud.githubusercontent.com/assets/360650/15955621/38567bf6-2f15-11e6-81fb-294f3b1d1352.png">

**Comment by MohammadSafwan** [comment]
@maina Have you added the Team Management Module along with the Rest Module on the server? Also, please tell me about the version of OpenMRS that is being used.

**Comment by maina** [comment]
@MohammadSafwan 
See the attached image. OpenMRS version - Version: 1.9.7 Build 60bd9b
<img width="1669" alt="screen shot 2016-06-10 at 4 10 25 pm" src="https://cloud.githubusercontent.com/assets/360650/15958096/0e6bd8c0-2f26-11e6-9a10-17c4d8842475.png">

**Comment by maimoonak** [comment]
@MohammadSafwan can you double check that they are using correct verision and if there is a build you have that is working is fine plz share with team/James on slack. @maina his slack name is mohammadsafwan .

**Comment by maina** [comment]
Fixed. @MohammadSafwan shared his working module. He's also to version it up to be the latest working module.
