### ISSUE TITLE
Module release 1.0.0 not working with OpenMRS 1.11.x+

### ISSUE THREAD

**Issue by maimoonak** [OpenSRP/openmrs-module-team#4]
Module release 1.0.0 not working with OpenMRS 1.11.x+;

It should be compatible with 1.9.2 to 2.0.x

**Comment by cafootitt** [comment]
@craigappl fyi

**Comment by craigappl** [comment]
Hi Everyone,

I did a triage today. Here are a few issues that need to be addressed:
- The [getUser method in the TeamMemberController](https://github.com/OpenSRP/openmrs-module-team/blob/0679a2801f783d0c2dd68bee4ab555eef80aeba4/omod/src/main/java/org/openmrs/module/teammodule/web/controller/TeamMemberController.java#L131) is full of depricated methods that are removed in OpenMRS Platform 2.0.
- They significantly changed the names of user privileges constants in OpenMRS platform 1.11, which may be the reason it's not working. The REST model are based on the old constants. [Here's the link to the current version.](https://github.com/openmrs/openmrs-core/blob/master/api/src/main/java/org/openmrs/util/PrivilegeConstants.java) You can flip through the 1.9.x, 1.10.x and 1.11.x release tags to show how they translated.
- The target build environment is Java 1.5. OpenMRS 1.10 and 1.11 are built with Java 1.7 and 2.0 is built with Java 1.8.
- OpenMRS 2.0 has a dependency on the openmrs-module-legacyui and [javax in the omod file](https://github.com/openmrs/openmrs-module-legacyui/blob/master/omod/pom.xml#L103) so the unit tests can be run.

I hope this helps. Please ping or tag me if you run into any problems.

**Comment by zohaibmk** [comment]
The module has been tested with 1.11.x and 2.0.x. The release can be found at: https://github.com/OpenSRP/openmrs-module-team/releases/tag/2.0.0b
